export const SITE = {
  website: "https://xiang-1208.github.io/xiang_blog",
  author: "潇翔",
  profile: "https://github.com/xiang-1208",
  desc: "一个技术博客，分享学习与思考",
  title: "潇翔的博客",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "zh",
  timezone: "Asia/Shanghai",
} as const;
